#!/usr/bin/env python3
"""Reproducibly extract Wine dwrite's OpenType shaping engine from upstream
`opentype.c` into a standalone translation unit for the pydwshape port.

Why: upstream `opentype.c` (6806 lines) mixes (a) OpenType type definitions and
raw table readers [1..~1337], (b) a COM font-analysis layer (ttc/ttf/otf
analyzer, cmap structs, name/metrics/color/var queries that talk to
IDWriteFontFileStream / IDWriteFontFace*) [~1338..3257] and (c) the GSUB/GPOS
shaping engine [~3258..6465]. For shaping we need (a)+(c); (b) is replaced by
our own raw-sfnt font driver.

Usage:
    python tools/wine_dwrite/port/tools/extract_engine.py \
        <wine-src/dlls/dwrite/opentype.c> <out-dir>

The line boundaries are asserted by matching anchor lines so the script fails
loudly if the upstream file moves.
"""
import os
import sys

# Boundaries are kept 1-based and INCLUSIVE. We keep opentype.c lines
# [1 .. head_end] and [engine_start .. engine_end]; everything between is the
# COM font-analysis layer we drop.
HEAD_END_PREFIX = "HRESULT opentype_try_get_font_table("  # first dropped line
ENGINE_START_PREFIX = "void opentype_layout_scriptshaping_cache_init("  # first kept engine line
ENGINE_END_NEXT_PREFIX = "BOOL opentype_has_vertical_variants("  # first line after the engine


def find_anchor(lines, anchor):
    for i, l in enumerate(lines, 1):
        if l.startswith(anchor):
            return i
    return -1


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    src, outdir = sys.argv[1], sys.argv[2]
    with open(src, "r", encoding="utf-8", errors="replace") as f:
        lines = f.read().split("\n")

    drop_start = find_anchor(lines, HEAD_END_PREFIX)          # 1st line of analysis
    engine_start = find_anchor(lines, ENGINE_START_PREFIX)    # 1st line of engine
    engine_after = find_anchor(lines, ENGINE_END_NEXT_PREFIX) # 1st line after engine
    if drop_start < 0 or engine_start < 0 or engine_after < 0:
        print("anchor(s) not found (drop_start=%d engine_start=%d engine_after=%d)"
              % (drop_start, engine_start, engine_after), file=sys.stderr)
        return 1

    # sanity: regions must be ordered and non-overlapping
    assert 1 < drop_start < engine_start < engine_after

    # 0-based slicing. Keep lines [1..drop_start-1] (head) and
    # [engine_start..engine_after-1] (engine).
    head = lines[:drop_start - 1]
    engine = lines[engine_start - 1: engine_after - 1]

    os.makedirs(outdir, exist_ok=True)
    out = os.path.join(outdir, "opentype_shaping.c")
    with open(out, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/wine_dwrite/port/tools/extract_engine.py \xe2\x80\x94 do not edit by hand.\n")
        f.write(" * Extracted from upstream Wine dlls/dwrite/opentype.c:\n")
        f.write(" *   head lines 1..%d (types + table_read helpers)\n" % (drop_start - 1))
        f.write(" *   engine lines %d..%d (GSUB/GPOS shaping core)\n" % (engine_start, engine_after - 1))
        f.write(" * Dropped: COM font-analysis layer (lines %d..%d).\n" % (drop_start, engine_start - 1))
        f.write(" * Upstream copyright/LGPL notice retained below.\n */\n\n")
        f.write("\n".join(head))
        f.write("\n\n/* ============ engine core (lines %d..%d of opentype.c) ============ */\n\n"
                % (engine_start, engine_after - 1))
        f.write("\n".join(engine))
        f.write("\n")
    print("wrote %s head=1..%d engine=%d..%d" % (out, drop_start - 1, engine_start, engine_after - 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
